name: overkeys
description: "An open-source, customizable on-screen keyboard for Windows. Learn and practice alternative layouts, personalize appearance, and improve your typing."
publish_to: "none"
version: 0.1.1
repository: https://github.com/conventoangelo/OverKeys

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.2
  tray_manager: ^0.2.3
  ffi: ^2.1.3
  win32: ^5.5.4
  desktop_multi_window: ^0.2.0
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.3.2
  flex_color_picker: ^3.6.0
  flutter_localizations:
    sdk: flutter
  intl: any
  launch_at_startup: ^0.3.1
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
        - asset: assets/fonts/GeistMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GeistMono-Bold.ttf
          weight: 700
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700

  assets:
    - assets/images/app_icon.ico
    - assets/images/app_icon.png
