name: Build macOS Release

on:
  release:
    types: [released]

jobs:
  build-macos:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos --release

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG with create-dmg
        run: |
          create-dmg \
            --volname "OverKeys" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            "OverKeys-${{ github.event.release.tag_name }}-macOS.dmg" \
            "build/macos/Build/Products/Release/overkeys.app"

      - name: Upload to Release
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            "OverKeys-${{ github.event.release.tag_name }}-macOS.dmg" \
            --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
